
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.farmersrespite]
			coffee_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.thermal]
			chocolate_cake = true
			spice_cake = true

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.applewood]
			apple = true

		[types.wood_type.meadow]
			pine = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

	[types.leaves_type]

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.meadow]
			pine = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			null = true
			cypress = true
			pine = true
			empyreal = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.upgrade_aquatic]
			river = true

	[types.cut_block_type]

		[types.cut_block_type.mcwroofs]
			white_roof = true
			light_gray_roof = true
			gray_roof = true
			black_roof = true
			base_roof = true

		[types.cut_block_type.mcwlights]
			redstone_lamp = true
			glowstone = true
			shroomlight = true
			sea_lantern = true

		[types.cut_block_type.mcwpaths]
			andesite_running_bond = true
			diorite_running_bond = true
			granite_running_bond = true
			sandstone_running_bond = true
			red_sandstone_running_bond = true
			brick_running_bond = true
			stone_running_bond = true
			mossy_stone_running_bond = true
			cobbled_deepslate_running_bond = true
			deepslate_running_bond = true
			mud_brick_running_bond = true
			blackstone_running_bond = true
			dark_prismarine_running_bond = true
			andesite_windmill_weave = true
			diorite_windmill_weave = true
			granite_windmill_weave = true
			sandstone_windmill_weave = true
			red_sandstone_windmill_weave = true
			brick_windmill_weave = true
			stone_windmill_weave = true
			mossy_stone_windmill_weave = true
			cobbled_deepslate_windmill_weave = true
			deepslate_windmill_weave = true
			mud_brick_windmill_weave = true
			blackstone_windmill_weave = true
			dark_prismarine_windmill_weave = true
			andesite_flagstone = true
			diorite_flagstone = true
			granite_flagstone = true
			sandstone_flagstone = true
			red_sandstone_flagstone = true
			brick_flagstone = true
			stone_flagstone = true
			mossy_stone_flagstone = true
			cobbled_deepslate_flagstone = true
			deepslate_flagstone = true
			mud_brick_flagstone = true
			blackstone_flagstone = true
			dark_prismarine_flagstone = true
			andesite_crystal_floor = true
			diorite_crystal_floor = true
			granite_crystal_floor = true
			sandstone_crystal_floor = true
			red_sandstone_crystal_floor = true
			brick_crystal_floor = true
			stone_crystal_floor = true
			mossy_stone_crystal_floor = true
			cobbled_deepslate_crystal_floor = true
			deepslate_crystal_floor = true
			mud_brick_crystal_floor = true
			blackstone_crystal_floor = true
			dark_prismarine_crystal_floor = true

		[types.cut_block_type.notreepunching]
			andesite_cobblestone = true
			diorite_cobblestone = true
			granite_cobblestone = true

		[types.cut_block_type.thermal]
			rubberwood = true

		[types.cut_block_type.finsandtails]
			flatback_shell_brick = true
			pebble_shell_brick = true
			siderol_shell_brick = true
			mixed_pebble_shell_brick = true
			mixed_flatback_shell_brick = true

		[types.cut_block_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			brimstone_brick = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.cut_block_type.vinery]
			dark_cherry = true
			loam = true
			coarse_dirt = true
			dirt = true
			grass = true
			dirt_path = true

		[types.cut_block_type.applewood]
			apple = true

		[types.cut_block_type.meadow]
			limestone = true
			cobbled_limestone = true
			limestone_brick = true
			mossy_cobbled_limestone = true
			mossy_limestone_brick = true
			pine = true

		[types.cut_block_type.biomeswevegone]
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			blue_sandstone = true
			smooth_blue_sandstone = true
			cut_blue_sandstone = true
			purple_sandstone = true
			smooth_purple_sandstone = true
			cut_purple_sandstone = true
			pink_sandstone = true
			smooth_pink_sandstone = true
			cut_pink_sandstone = true
			windswept_sandstone = true
			smooth_windswept_sandstone = true
			cut_windswept_sandstone = true
			dacite = true
			dacite_brick = true
			dacite_cobblestone = true
			dacite_tile = true
			red_rock = true
			red_rock_brick = true
			cracked_red_rock_brick = true
			chiseled_red_rock_brick = true
			mossy_red_rock_brick = true
			mossy_stone = true
			rocky_stone = true
			cattail_thatch = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.cut_block_type.neapolitan]
			chocolate_brick = true
			chocolate_tile = true
			frond_thatch = true

		[types.cut_block_type.buzzier_bees]
			honeycomb_brick = true
			honeycomb_tile = true

		[types.cut_block_type.alexscaves]
			galena = true
			galena_brick = true
			limestone = true
			smooth_limestone = true
			pewen = true
			radrock = true
			radrock_brick = true
			cinder_block = true
			abyssmarine = true
			abyssmarine_brick = true
			smooth_bone = true
			guanostone = true
			guanostone_brick = true
			coprolith = true
			smooth_coprolith = true
			thornwood = true
			gingerbread_brick = true
			frosted_gingerbread_brick = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.yungscavebiomes]
			smooth_ancient_sandstone = true
			cut_ancient_sandstone = true
			ancient_sandstone = true

		[types.cut_block_type.galosphere]
			silver_tiles = true
			silver_panel = true
			smooth_amethyst = true
			smooth_allurite = true
			smooth_lumiere = true
			amethyst_brick = true
			allurite_brick = true
			lumiere_brick = true
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true
			polished_pink_salt = true
			polished_rose_pink_salt = true
			polished_pastel_pink_salt = true
			pink_salt_brick = true
			rose_pink_salt_brick = true
			pastel_pink_salt_brick = true

		[types.cut_block_type.betterarcheology]
			rotten = true
			cracked_mud_brick = true

		[types.cut_block_type.mowziesmobs]
			painted_acacia = true

		[types.cut_block_type.savage_and_ravage]
			gloomy_tile = true

		[types.cut_block_type.upgrade_aquatic]
			beachgrass_thatch = true
			luminous_prismarine = true
			tooth_brick = true
			scute_shingle = true
			scute_pavement = true
			coralstone = true
			bubble_coralstone = true
			horn_coralstone = true
			tube_coralstone = true
			brain_coralstone = true
			fire_coralstone = true
			acan_coralstone = true
			finger_coralstone = true
			star_coralstone = true
			moss_coralstone = true
			petal_coralstone = true
			branch_coralstone = true
			rock_coralstone = true
			pillow_coralstone = true
			silk_coralstone = true
			chrome_coralstone = true
			prismarine_coralstone = true
			elder_prismarine_coralstone = true
			dead_coralstone = true
			kelpy_cobblestone = true
			kelpy_stone_brick = true
			kelpy_cobblestone_brick = true
			kelpy_cobblestone_tile = true
			driftwood = true
			river = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			desk = true
			cutting_board = true
			drawer = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			kitchen_cabinetry = true
			crate = true
			chair = true
			light_ceiling_fan = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			glass_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			beach_door = true
			waffle_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			cottage_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			barn_door = true
			mystic_door = true
			bark_glass_door = true
			classic_door = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwstairs]
			terrace_stairs = true
			compact_stairs = true
			balcony = true
			loft_stairs = true
			railing = true
			platform = true
			skyline_stairs = true
			bulk_stairs = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwlights]
			tiki_torch = true
			soul_tiki_torch = true
			ceiling_fan_light = true

		[entries.wood_type.friendsandfoes]
			beehive = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

